### ISSUE TITLE
Compatibility with Laravel 5.6?

### ISSUE THREAD

**Issue by laurencei** [vinkla/laravel-algolia#10]
Is this package compatibile with Laravel 5.6?

In composer.json

```
        "laravel/framework": "5.6.*",
        "vinkla/algolia": "2.7.*"
```

gives

![image](https://user-images.githubusercontent.com/1210658/36070705-e85dbdec-0f43-11e8-9b4d-c75250431065.png)

Is there any reason this package is limited to Laravel 5.5? Or can we bump the version dependancy up?

**Comment by vinkla** [comment]
Laravel 5.6 support isn't possible just yet: https://github.com/GrahamCampbell/Laravel-Manager/pull/11#issuecomment-364654625

**Comment by vinkla** [comment]
Laravel 5.6 support has been added in version 3.0.

**Comment by laurencei** [comment]
thnkas @vinkla
