### ISSUE TITLE
Release 2.4.1 with 5.4 support?

### ISSUE THREAD

**Issue by inxilpro** [vinkla/laravel-algolia#7]
Laravel 5.4 supports PHP >=5.6.4, but you dropped PHP 5 support in the only version that's marked as compatible with illuminate/support@5.4. Looking at the changelog between 2.4.0 and 2.5.0 it looks like the only changes were adding some PHP 7 language features, so the 2.4.0 release should be 100% compatible with Laravel 5.4.

A simple fix would be to release a 2.4.1 version that just adds Laravel 5.4 to the require section:

```json
"require": {
    "php": "^5.6.4 || ^7.0",
    "illuminate/contracts": "5.1.* || 5.2.* || 5.3.* || 5.4.*",
    "illuminate/support": "5.1.* || 5.2.* || 5.3.* || 5.4.*",
    "graham-campbell/manager": "^2.4",
    "algolia/algoliasearch-client-php": "^1.6.3"
},
```

I was going to submit a PR, but you don't have a branch to submit against. See https://github.com/inxilpro/laravel-algolia/commit/7cd858da7c6220b5d6d411e1d55b83b4cdb3bdf1

Cheers,

Chris

**Comment by vinkla** [comment]
I get your point but I wanted to benefit from new changes in PHP 7.0 and decided to drop 5.6 from all my packages. I wont release a new version for PHP 5.6. All major PHP frameworks will most likely drop PHP 5.* support this year. Thanks for the suggestion though.
