### ISSUE TITLE
Support for Laravel 5.4 using PHP 5.6.4+

### ISSUE THREAD

**Issue by jsefton** [vinkla/laravel-algolia#8]
The core of Laravel base requirement is PHP 5.6.4, but the only support in this package for Laravel 5.4 is PHP 7.0+. This limits out the usage the package by many people still running on 5.6.4.

Simple changes to the Service Providers to remove the declare strict types and removal of the declare types throughout as on line 121 of the service provider.

**Comment by vinkla** [comment]
I see your point but almost all major PHP frameworks will drop PHP 5 support this year. We're just one step ahead. The community should update as well. There are huge benefits upgrading to PHP 7. I won't add PHP 5 support back in. Sorry.
